# Generated by Django 5.0.3 on 2024-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('payment', models.TextField()),
                ('work_hours', models.TextField()),
                ('phys_lvl', models.IntegerField()),
                ('kind_of_job', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
