# Generated by Django 5.0.2 on 2024-03-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
