# Generated by Django 5.0.3 on 2024-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='kind_of_job',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='phys_lvl',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_hours',
            field=models.TextField(blank=True),
        ),
    ]
