# Generated by Django 5.0.2 on 2024-03-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorites',
        ),
    ]
