# Generated by Django 5.0.3 on 2024-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_description_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phys_lvl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
