# Generated by Django 5.0.2 on 2024-03-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_my_posts_remove_user_favorites_and_more'),
        ('posts', '0006_remove_post_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_posts', to='login.user'),
        ),
    ]
