# Generated by Django 5.0.3 on 2024-03-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
