# Generated by Django 5.0.3 on 2024-03-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_post_created_by_post_created_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_y',
        ),
    ]
