# Generated by Django 5.0.3 on 2024-03-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
