# Generated by Django 5.0.2 on 2024-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('favorites', models.ManyToManyField(related_name='favorited_by', to='login.user')),
                ('my_posts', models.ManyToManyField(related_name='authored_by', to='login.user')),
            ],
        ),
    ]
