# Generated by Django 5.0.3 on 2024-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_posts',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='my_posts',
            field=models.JSONField(default=list),
        ),
    ]
