# Generated by Django 5.0.3 on 2024-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='no_name'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='user',
            name='my_posts',
            field=models.ManyToManyField(related_name='authored_by', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.JSONField(default=list),
        ),
    ]
