# Generated by Django 5.0.2 on 2024-03-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_age_alter_user_mail_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='my_posts',
            field=models.JSONField(default=list),
        ),
    ]
