# Generated by Django 5.0.3 on 2024-03-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_name_alter_user_age_remove_user_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
