# Generated by Django 5.0.2 on 2024-03-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_favorites_remove_user_my_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
    ]
