# Generated by Django 5.0.3 on 2024-03-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_user_rank_user_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rating',
            new_name='site_rating',
        ),
    ]
