# Generated by Django 5.0.2 on 2024-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_my_posts_remove_user_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_posts',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.JSONField(default=list),
        ),
    ]
