# Generated by Django 5.0.3 on 2024-03-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_user_phone_user_site_rating_delete_siterating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
