# Generated by Django 5.0.2 on 2024-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_user_favorites'),
        ('posts', '0008_remove_post_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='posts.post'),
        ),
    ]
