# Generated by Django 5.0.2 on 2024-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_user_favorites'),
        ('posts', '0008_remove_post_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_posts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='posts.post'),
        ),
    ]
