# Generated by Django 5.0.2 on 2024-03-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_user_my_posts_alter_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.JSONField(default=list),
        ),
    ]
