# Generated by Django 5.0.3 on 2024-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_user_favorites_alter_user_my_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_posts',
            field=models.JSONField(default=list),
        ),
    ]
